/* Generated by Together */

using System;
using System.Resources;
using Ferda.FrontEnd.Menu;


namespace Ferda 
{
    namespace FrontEnd 
    {

        /// <summary>
		/// Ordinary StatusBar
		/// </summary>
        internal class FerdaStatusBar : System.Windows.Forms.StatusStrip
        {
/*
            //Resource manager from the FerdaForm
            private ResourceManager resManager;
            private ILocalizationManager localizationManager;

            /// <summary>
            /// Resource manager of the application, it is filled according to the
            /// current localization
            /// </summary>
            public ResourceManager ResManager
            {
                set
                {
                    resManager = value;
                }
                get
                {
                    if (resManager == null)
                    {
                        throw new ApplicationException(
                            "Desktop.ResManager cannot be null");
                    }
                    return resManager;
                }
            }

            ///<summary>
            /// Default constructor for FerdaStatusBar class.
            ///<summary>
            public FerdaStatusBar(ILocalizationManager lockManager)
                : base()
            {
                localizationManager = lockManager;
                ResManager = localizationManager.ResManager;
            }
 */
            public FerdaStatusBar()
                : base()
            {
            }
		}
 
    }
}
