//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferda.FrontEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferda.FrontEnd.Localization_en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferda is a user friendly data mining tool. It is a modular distributed multiplatform framework based on Internet Communications Engine. Ferda is very powerful in working with association rules..
        /// </summary>
        internal static string AboutDialogDescription {
            get {
                return ResourceManager.GetString("AboutDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers:.
        /// </summary>
        internal static string AboutDialogDevelopers {
            get {
                return ResourceManager.GetString("AboutDialogDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ferda DataMiner.
        /// </summary>
        internal static string AboutDialogText {
            get {
                return ResourceManager.GetString("AboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string AboutDialogVersion {
            get {
                return ResourceManager.GetString("AboutDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Against connections.
        /// </summary>
        internal static string ArchiveAgainstText {
            get {
                return ResourceManager.GetString("ArchiveAgainstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ArchiveAllText {
            get {
                return ResourceManager.GetString("ArchiveAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Along connections.
        /// </summary>
        internal static string ArchiveAlongText {
            get {
                return ResourceManager.GetString("ArchiveAlongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string ArchiveContentText {
            get {
                return ResourceManager.GetString("ArchiveContentText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string BoxExceptionDailogBox {
            get {
                return ResourceManager.GetString("BoxExceptionDailogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Exception.
        /// </summary>
        internal static string BoxExceptionDialogCaption {
            get {
                return ResourceManager.GetString("BoxExceptionDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details:.
        /// </summary>
        internal static string BoxExceptionDialogDetails {
            get {
                return ResourceManager.GetString("BoxExceptionDialogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has thrown an exception..
        /// </summary>
        internal static string BoxExceptionDialogKecy {
            get {
                return ResourceManager.GetString("BoxExceptionDialogKecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Help.
        /// </summary>
        internal static string ContextHelpContentText {
            get {
                return ResourceManager.GetString("ContextHelpContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting from archive.
        /// </summary>
        internal static string DeleteFromArchiveCaption {
            get {
                return ResourceManager.GetString("DeleteFromArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the box from archive? It will be deleted from all the views in the project!.
        /// </summary>
        internal static string DeleteFromArchiveMessage {
            get {
                return ResourceManager.GetString("DeleteFromArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string DesktopBadConnectionCaption {
            get {
                return ResourceManager.GetString("DesktopBadConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection can be added only from an output connector of a box to an input connector of other box..
        /// </summary>
        internal static string DesktopBadConnectionDescription {
            get {
                return ResourceManager.GetString("DesktopBadConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incosistence in box and socket type.
        /// </summary>
        internal static string DesktopBadConnectionInvalidType {
            get {
                return ResourceManager.GetString("DesktopBadConnectionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string DesktopBoxAlreadyExistsCaption {
            get {
                return ResourceManager.GetString("DesktopBoxAlreadyExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view already contains this box.
        /// </summary>
        internal static string DesktopBoxAlreadyExistsText {
            get {
                return ResourceManager.GetString("DesktopBoxAlreadyExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string DesktopCannotWriteCaption {
            get {
                return ResourceManager.GetString("DesktopCannotWriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect a box because the box is locked by other box.
        /// </summary>
        internal static string DesktopCannotWriteText {
            get {
                return ResourceManager.GetString("DesktopCannotWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Connection.
        /// </summary>
        internal static string DesktopDeleteConnection {
            get {
                return ResourceManager.GetString("DesktopDeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string DesktopLayout {
            get {
                return ResourceManager.GetString("DesktopLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The socket does not allow more than one connected boxes.
        /// </summary>
        internal static string DesktopMoreThanOneErrorText {
            get {
                return ResourceManager.GetString("DesktopMoreThanOneErrorText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ferda64 {
            get {
                object obj = ResourceManager.GetObject("ferda64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadins add-ins ....
        /// </summary>
        internal static string LoadingAddIns {
            get {
                return ResourceManager.GetString("LoadingAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading archive ....
        /// </summary>
        internal static string LoadingArchive {
            get {
                return ResourceManager.GetString("LoadingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading context help...
        /// </summary>
        internal static string LoadingContextHelp {
            get {
                return ResourceManager.GetString("LoadingContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading desktop ....
        /// </summary>
        internal static string LoadingDesktop {
            get {
                return ResourceManager.GetString("LoadingDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading docking ....
        /// </summary>
        internal static string LoadingDocking {
            get {
                return ResourceManager.GetString("LoadingDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading icons ....
        /// </summary>
        internal static string LoadingIcons {
            get {
                return ResourceManager.GetString("LoadingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading menus ....
        /// </summary>
        internal static string LoadingMenus {
            get {
                return ResourceManager.GetString("LoadingMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading new boxes ... .
        /// </summary>
        internal static string LoadingNewBox {
            get {
                return ResourceManager.GetString("LoadingNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Project Manager....
        /// </summary>
        internal static string LoadingProjectManager {
            get {
                return ResourceManager.GetString("LoadingProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading properties ....
        /// </summary>
        internal static string LoadingProperties {
            get {
                return ResourceManager.GetString("LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading SVG ....
        /// </summary>
        internal static string LoadingSVG {
            get {
                return ResourceManager.GetString("LoadingSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the localization of the application.
        /// </summary>
        internal static string LocalizationLabel {
            get {
                return ResourceManager.GetString("LocalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization will be changed during the next start of the application.
        /// </summary>
        internal static string LocalizationLabel2 {
            get {
                return ResourceManager.GetString("LocalizationLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string LocalizationTab {
            get {
                return ResourceManager.GetString("LocalizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a group box.
        /// </summary>
        internal static string MakeGroup {
            get {
                return ResourceManager.GetString("MakeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string MenuActions {
            get {
                return ResourceManager.GetString("MenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuArchiveDelete {
            get {
                return ResourceManager.GetString("MenuArchiveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string MenuDesktop {
            get {
                return ResourceManager.GetString("MenuDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Desktop.
        /// </summary>
        internal static string MenuDesktopNewDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopNewDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Desktop.
        /// </summary>
        internal static string MenuDesktopOpenDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopOpenDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Desktop.
        /// </summary>
        internal static string MenuDesktopRemoveDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopRemoveDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string MenuEditClone {
            get {
                return ResourceManager.GetString("MenuEditClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MenuEditCopy {
            get {
                return ResourceManager.GetString("MenuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from Archive.
        /// </summary>
        internal static string MenuEditDeleteFromArchive {
            get {
                return ResourceManager.GetString("MenuEditDeleteFromArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from Desktop.
        /// </summary>
        internal static string MenuEditDeleteFromDesktop {
            get {
                return ResourceManager.GetString("MenuEditDeleteFromDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MenuEditHide {
            get {
                return ResourceManager.GetString("MenuEditHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize in Archive.
        /// </summary>
        internal static string MenuEditLocalizeInArchive {
            get {
                return ResourceManager.GetString("MenuEditLocalizeInArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Box.
        /// </summary>
        internal static string MenuEditNewBox {
            get {
                return ResourceManager.GetString("MenuEditNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack all Sockets.
        /// </summary>
        internal static string MenuEditPackAllSockets {
            get {
                return ResourceManager.GetString("MenuEditPackAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Socket.
        /// </summary>
        internal static string MenuEditPackSocket {
            get {
                return ResourceManager.GetString("MenuEditPackSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string MenuEditPaste {
            get {
                return ResourceManager.GetString("MenuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MenuEditRename {
            get {
                return ResourceManager.GetString("MenuEditRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack all Layers.
        /// </summary>
        internal static string MenuEditUnpackAllLayers {
            get {
                return ResourceManager.GetString("MenuEditUnpackAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack all Layers all Sockets.
        /// </summary>
        internal static string MenuEditUnpackAllLayersAllSockets {
            get {
                return ResourceManager.GetString("MenuEditUnpackAllLayersAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack one layer.
        /// </summary>
        internal static string MenuEditUnpackOneLayer {
            get {
                return ResourceManager.GetString("MenuEditUnpackOneLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack one layer of all Sockets.
        /// </summary>
        internal static string MenuEditUnpackOneLayerAllSockets {
            get {
                return ResourceManager.GetString("MenuEditUnpackOneLayerAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string MenuFileAllFiles {
            get {
                return ResourceManager.GetString("MenuFileAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferda project files.
        /// </summary>
        internal static string MenuFileFerdaProjectFiles {
            get {
                return ResourceManager.GetString("MenuFileFerdaProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string MenuFileNewProject {
            get {
                return ResourceManager.GetString("MenuFileNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string MenuFileOpenProject {
            get {
                return ResourceManager.GetString("MenuFileOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current project?.
        /// </summary>
        internal static string MenuFileSaveChanges {
            get {
                return ResourceManager.GetString("MenuFileSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string MenuFileSaveProject {
            get {
                return ResourceManager.GetString("MenuFileSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as.
        /// </summary>
        internal static string MenuFileSaveProjectAs {
            get {
                return ResourceManager.GetString("MenuFileSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Ferda.
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferda Help.
        /// </summary>
        internal static string MenuHelpApplicationHelp {
            get {
                return ResourceManager.GetString("MenuHelpApplicationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theoretical Help.
        /// </summary>
        internal static string MenuHelpTheoreticalHelp {
            get {
                return ResourceManager.GetString("MenuHelpTheoreticalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules asking for creation.
        /// </summary>
        internal static string MenuModulesAskingCreation {
            get {
                return ResourceManager.GetString("MenuModulesAskingCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules for interaction.
        /// </summary>
        internal static string MenuModulesForInteraction {
            get {
                return ResourceManager.GetString("MenuModulesForInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New desktop.
        /// </summary>
        internal static string MenuNewViewName {
            get {
                return ResourceManager.GetString("MenuNewViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string MenuToolsPreferences {
            get {
                return ResourceManager.GetString("MenuToolsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string MenuViewArchive {
            get {
                return ResourceManager.GetString("MenuViewArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Help.
        /// </summary>
        internal static string MenuViewContextHelp {
            get {
                return ResourceManager.GetString("MenuViewContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Boxes.
        /// </summary>
        internal static string MenuViewNewBox {
            get {
                return ResourceManager.GetString("MenuViewNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Grid.
        /// </summary>
        internal static string MenuViewPropertyGrid {
            get {
                return ResourceManager.GetString("MenuViewPropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolBar.
        /// </summary>
        internal static string MenuViewToolBar {
            get {
                return ResourceManager.GetString("MenuViewToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Boxes.
        /// </summary>
        internal static string NewBoxContentText {
            get {
                return ResourceManager.GetString("NewBoxContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a desktop.
        /// </summary>
        internal static string OpenDesktopDialogCaption {
            get {
                return ResourceManager.GetString("OpenDesktopDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenDesktopDialogOK {
            get {
                return ResourceManager.GetString("OpenDesktopDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string PreferencesDialogCaption {
            get {
                return ResourceManager.GetString("PreferencesDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors have occured while loading the project.
        /// </summary>
        internal static string ProjectLoadErrorCaption {
            get {
                return ResourceManager.GetString("ProjectLoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not fount.
        /// </summary>
        internal static string ProjectLoadFileNotFound {
            get {
                return ResourceManager.GetString("ProjectLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        internal static string PropertiesCannotWriteCaption {
            get {
                return ResourceManager.GetString("PropertiesCannotWriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a box property because the box is locked by other box.
        /// </summary>
        internal static string PropertiesCannotWriteText {
            get {
                return ResourceManager.GetString("PropertiesCannotWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesContentText {
            get {
                return ResourceManager.GetString("PropertiesContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string PropertiesOutputConnector {
            get {
                return ResourceManager.GetString("PropertiesOutputConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the connections for this socket.
        /// </summary>
        internal static string PropertyConnectorDescription {
            get {
                return ResourceManager.GetString("PropertyConnectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets if the property is visible as a socket.
        /// </summary>
        internal static string PropertySocketHint {
            get {
                return ResourceManager.GetString("PropertySocketHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible sockets.
        /// </summary>
        internal static string PropertySocketName {
            get {
                return ResourceManager.GetString("PropertySocketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a desktop.
        /// </summary>
        internal static string RemoveDesktopDialogCaption {
            get {
                return ResourceManager.GetString("RemoveDesktopDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveDesktopDialogOK {
            get {
                return ResourceManager.GetString("RemoveDesktopDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a new box name.
        /// </summary>
        internal static string RenameDialogCaption {
            get {
                return ResourceManager.GetString("RenameDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the property to another value.
        /// </summary>
        internal static string StringComboAddingControlButtonText {
            get {
                return ResourceManager.GetString("StringComboAddingControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write another value:.
        /// </summary>
        internal static string StringComboAddingControlText {
            get {
                return ResourceManager.GetString("StringComboAddingControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User note.
        /// </summary>
        internal static string UserNote {
            get {
                return ResourceManager.GetString("UserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User note for box: .
        /// </summary>
        internal static string UserNoteCaption {
            get {
                return ResourceManager.GetString("UserNoteCaption", resourceCulture);
            }
        }
    }
}
