//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferda.FrontEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferda.FrontEnd.Localization_cs-CZ", typeof(Localization_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferda je uživatelsky přívětivý prostředek pro dobývání znalostí. Používá modulární multiplatformní systému používajícím Internet Communications Engine. Ferda se dá dobře použít zejména při práci s asociačními pravidly. .
        /// </summary>
        internal static string AboutDialogDescription {
            get {
                return ResourceManager.GetString("AboutDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyvinuli: .
        /// </summary>
        internal static string AboutDialogDevelopers {
            get {
                return ResourceManager.GetString("AboutDialogDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci Ferda DataMiner.
        /// </summary>
        internal static string AboutDialogText {
            get {
                return ResourceManager.GetString("AboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verze: .
        /// </summary>
        internal static string AboutDialogVersion {
            get {
                return ResourceManager.GetString("AboutDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Acrobat Reader nebyl nalezen.
        /// </summary>
        internal static string AcrobatNotFoundCaption {
            get {
                return ResourceManager.GetString("AcrobatNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyste mohli používat Ferdovu nápovědu, musíte mít na svém počítači nainstalován Adobe Acrobat Reader verze minimálně 6.0.
        /// </summary>
        internal static string AcrobatNotFoundText {
            get {
                return ResourceManager.GetString("AcrobatNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proti směru zapojení.
        /// </summary>
        internal static string ArchiveAgainstText {
            get {
                return ResourceManager.GetString("ArchiveAgainstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny.
        /// </summary>
        internal static string ArchiveAllText {
            get {
                return ResourceManager.GetString("ArchiveAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po směru zapojení.
        /// </summary>
        internal static string ArchiveAlongText {
            get {
                return ResourceManager.GetString("ArchiveAlongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archív.
        /// </summary>
        internal static string ArchiveContentText {
            get {
                return ResourceManager.GetString("ArchiveContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V krabičce.
        /// </summary>
        internal static string BoxExceptionDailogBox {
            get {
                return ResourceManager.GetString("BoxExceptionDailogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výjimka krabičky.
        /// </summary>
        internal static string BoxExceptionDialogCaption {
            get {
                return ResourceManager.GetString("BoxExceptionDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti výjimky:.
        /// </summary>
        internal static string BoxExceptionDialogDetails {
            get {
                return ResourceManager.GetString("BoxExceptionDialogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nastala výjimka..
        /// </summary>
        internal static string BoxExceptionDialogKecy {
            get {
                return ResourceManager.GetString("BoxExceptionDialogKecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontextová nápověda.
        /// </summary>
        internal static string ContextHelpContentText {
            get {
                return ResourceManager.GetString("ContextHelpContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak začít ve Ferdovi?.
        /// </summary>
        internal static string ContextHelpStart {
            get {
                return ResourceManager.GetString("ContextHelpStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazání z archivu.
        /// </summary>
        internal static string DeleteFromArchiveCaption {
            get {
                return ResourceManager.GetString("DeleteFromArchiveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat krabičku z archivu? Tímto se vymaže i ze všech pohledů!.
        /// </summary>
        internal static string DeleteFromArchiveMessage {
            get {
                return ResourceManager.GetString("DeleteFromArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba připojení.
        /// </summary>
        internal static string DesktopBadConnectionCaption {
            get {
                return ResourceManager.GetString("DesktopBadConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lze připojit vždy pouze z výstupního konektoru krabičky do vstupního konktoru jiné krabičky..
        /// </summary>
        internal static string DesktopBadConnectionDescription {
            get {
                return ResourceManager.GetString("DesktopBadConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nekonzistence typu socketu a krabičky.
        /// </summary>
        internal static string DesktopBadConnectionInvalidType {
            get {
                return ResourceManager.GetString("DesktopBadConnectionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string DesktopBoxAlreadyExistsCaption {
            get {
                return ResourceManager.GetString("DesktopBoxAlreadyExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracovní plocha už tuto krabičku obsahuje.
        /// </summary>
        internal static string DesktopBoxAlreadyExistsText {
            get {
                return ResourceManager.GetString("DesktopBoxAlreadyExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba zapojení.
        /// </summary>
        internal static string DesktopCannotWriteCaption {
            get {
                return ResourceManager.GetString("DesktopCannotWriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze zapojit krabičku, protože ji uzamkla jiná krabička.
        /// </summary>
        internal static string DesktopCannotWriteText {
            get {
                return ResourceManager.GetString("DesktopCannotWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat připojení.
        /// </summary>
        internal static string DesktopDeleteConnection {
            get {
                return ResourceManager.GetString("DesktopDeleteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozvržení grafu.
        /// </summary>
        internal static string DesktopLayout {
            get {
                return ResourceManager.GetString("DesktopLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zásuvka nepovoluje zapojení více než jedné krabičky..
        /// </summary>
        internal static string DesktopMoreThanOneErrorText {
            get {
                return ResourceManager.GetString("DesktopMoreThanOneErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ferduvNavod.pdf.
        /// </summary>
        internal static string FerdaTutorial {
            get {
                return ResourceManager.GetString("FerdaTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uzivprostredi.pdf.
        /// </summary>
        internal static string FerdaUserEnvironment {
            get {
                return ResourceManager.GetString("FerdaUserEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace přídavných modulů... .
        /// </summary>
        internal static string LoadingAddIns {
            get {
                return ResourceManager.GetString("LoadingAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace archivu ....
        /// </summary>
        internal static string LoadingArchive {
            get {
                return ResourceManager.GetString("LoadingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace kontextové nápovědy....
        /// </summary>
        internal static string LoadingContextHelp {
            get {
                return ResourceManager.GetString("LoadingContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace pracovních ploch ....
        /// </summary>
        internal static string LoadingDesktop {
            get {
                return ResourceManager.GetString("LoadingDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace dokování ....
        /// </summary>
        internal static string LoadingDocking {
            get {
                return ResourceManager.GetString("LoadingDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace ikon ....
        /// </summary>
        internal static string LoadingIcons {
            get {
                return ResourceManager.GetString("LoadingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace menu ....
        /// </summary>
        internal static string LoadingMenus {
            get {
                return ResourceManager.GetString("LoadingMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace nových krabiček ....
        /// </summary>
        internal static string LoadingNewBox {
            get {
                return ResourceManager.GetString("LoadingNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace Project Manageru....
        /// </summary>
        internal static string LoadingProjectManager {
            get {
                return ResourceManager.GetString("LoadingProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace vlastností ... .
        /// </summary>
        internal static string LoadingProperties {
            get {
                return ResourceManager.GetString("LoadingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializace SVG ....
        /// </summary>
        internal static string LoadingSVG {
            get {
                return ResourceManager.GetString("LoadingSVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte lokalizaci aplikace.
        /// </summary>
        internal static string LocalizationLabel {
            get {
                return ResourceManager.GetString("LocalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizace se změní při dalším startu aplikace.
        /// </summary>
        internal static string LocalizationLabel2 {
            get {
                return ResourceManager.GetString("LocalizationLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizace.
        /// </summary>
        internal static string LocalizationTab {
            get {
                return ResourceManager.GetString("LocalizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit krabičku skupina.
        /// </summary>
        internal static string MakeGroup {
            get {
                return ResourceManager.GetString("MakeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        internal static string MenuActions {
            get {
                return ResourceManager.GetString("MenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        internal static string MenuArchiveDelete {
            get {
                return ResourceManager.GetString("MenuArchiveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracovní plocha.
        /// </summary>
        internal static string MenuDesktop {
            get {
                return ResourceManager.GetString("MenuDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová pracovní plocha.
        /// </summary>
        internal static string MenuDesktopNewDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopNewDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřit pracovní plochu.
        /// </summary>
        internal static string MenuDesktopOpenDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopOpenDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit pracovní plochu.
        /// </summary>
        internal static string MenuDesktopRemoveDesktop {
            get {
                return ResourceManager.GetString("MenuDesktopRemoveDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úpravy.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klonovat.
        /// </summary>
        internal static string MenuEditClone {
            get {
                return ResourceManager.GetString("MenuEditClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopírovat.
        /// </summary>
        internal static string MenuEditCopy {
            get {
                return ResourceManager.GetString("MenuEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit z archivu.
        /// </summary>
        internal static string MenuEditDeleteFromArchive {
            get {
                return ResourceManager.GetString("MenuEditDeleteFromArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit z pracovní plochy.
        /// </summary>
        internal static string MenuEditDeleteFromDesktop {
            get {
                return ResourceManager.GetString("MenuEditDeleteFromDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrýt.
        /// </summary>
        internal static string MenuEditHide {
            get {
                return ResourceManager.GetString("MenuEditHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizuj v archivu.
        /// </summary>
        internal static string MenuEditLocalizeInArchive {
            get {
                return ResourceManager.GetString("MenuEditLocalizeInArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová krabička.
        /// </summary>
        internal static string MenuEditNewBox {
            get {
                return ResourceManager.GetString("MenuEditNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabal všechny zapojení.
        /// </summary>
        internal static string MenuEditPackAllSockets {
            get {
                return ResourceManager.GetString("MenuEditPackAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabalit zapojení.
        /// </summary>
        internal static string MenuEditPackSocket {
            get {
                return ResourceManager.GetString("MenuEditPackSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vložit.
        /// </summary>
        internal static string MenuEditPaste {
            get {
                return ResourceManager.GetString("MenuEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znovu.
        /// </summary>
        internal static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejmenovat.
        /// </summary>
        internal static string MenuEditRename {
            get {
                return ResourceManager.GetString("MenuEditRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        internal static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbal všechny vrstvy.
        /// </summary>
        internal static string MenuEditUnpackAllLayers {
            get {
                return ResourceManager.GetString("MenuEditUnpackAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbal všechny vrstvy všech zapojení.
        /// </summary>
        internal static string MenuEditUnpackAllLayersAllSockets {
            get {
                return ResourceManager.GetString("MenuEditUnpackAllLayersAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbalit jednu vrstvu.
        /// </summary>
        internal static string MenuEditUnpackOneLayer {
            get {
                return ResourceManager.GetString("MenuEditUnpackOneLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozbal jednu vrstvu všech zapojení.
        /// </summary>
        internal static string MenuEditUnpackOneLayerAllSockets {
            get {
                return ResourceManager.GetString("MenuEditUnpackOneLayerAllSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny soubory.
        /// </summary>
        internal static string MenuFileAllFiles {
            get {
                return ResourceManager.GetString("MenuFileAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory Ferda Project.
        /// </summary>
        internal static string MenuFileFerdaProjectFiles {
            get {
                return ResourceManager.GetString("MenuFileFerdaProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový projekt.
        /// </summary>
        internal static string MenuFileNewProject {
            get {
                return ResourceManager.GetString("MenuFileNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít projekt.
        /// </summary>
        internal static string MenuFileOpenProject {
            get {
                return ResourceManager.GetString("MenuFileOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední projekty.
        /// </summary>
        internal static string MenuFileRecentProjects {
            get {
                return ResourceManager.GetString("MenuFileRecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete uložit stávající projekt?.
        /// </summary>
        internal static string MenuFileSaveChanges {
            get {
                return ResourceManager.GetString("MenuFileSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit projekt.
        /// </summary>
        internal static string MenuFileSaveProject {
            get {
                return ResourceManager.GetString("MenuFileSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit projekt jako.
        /// </summary>
        internal static string MenuFileSaveProjectAs {
            get {
                return ResourceManager.GetString("MenuFileSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Ferdovi.
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda aplikace Ferda.
        /// </summary>
        internal static string MenuHelpApplicationHelp {
            get {
                return ResourceManager.GetString("MenuHelpApplicationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teoretická nápověda.
        /// </summary>
        internal static string MenuHelpTheoreticalHelp {
            get {
                return ResourceManager.GetString("MenuHelpTheoreticalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdův návod.
        /// </summary>
        internal static string MenuHelpTutorial {
            get {
                return ResourceManager.GetString("MenuHelpTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krabičky nabízené na vytvoření.
        /// </summary>
        internal static string MenuModulesAskingCreation {
            get {
                return ResourceManager.GetString("MenuModulesAskingCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moduly pro interakci.
        /// </summary>
        internal static string MenuModulesForInteraction {
            get {
                return ResourceManager.GetString("MenuModulesForInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová pracovní plocha.
        /// </summary>
        internal static string MenuNewViewName {
            get {
                return ResourceManager.GetString("MenuNewViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástroje.
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnosti.
        /// </summary>
        internal static string MenuToolsPreferences {
            get {
                return ResourceManager.GetString("MenuToolsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiv.
        /// </summary>
        internal static string MenuViewArchive {
            get {
                return ResourceManager.GetString("MenuViewArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontextovou nápovědu.
        /// </summary>
        internal static string MenuViewContextHelp {
            get {
                return ResourceManager.GetString("MenuViewContextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové krabičky.
        /// </summary>
        internal static string MenuViewNewBox {
            get {
                return ResourceManager.GetString("MenuViewNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnosti.
        /// </summary>
        internal static string MenuViewPropertyGrid {
            get {
                return ResourceManager.GetString("MenuViewPropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel nástrojů.
        /// </summary>
        internal static string MenuViewToolBar {
            get {
                return ResourceManager.GetString("MenuViewToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové krabičky.
        /// </summary>
        internal static string NewBoxContentText {
            get {
                return ResourceManager.GetString("NewBoxContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít pracovní plochu.
        /// </summary>
        internal static string OpenDesktopDialogCaption {
            get {
                return ResourceManager.GetString("OpenDesktopDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít.
        /// </summary>
        internal static string OpenDesktopDialogOK {
            get {
                return ResourceManager.GetString("OpenDesktopDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnosti.
        /// </summary>
        internal static string PreferencesDialogCaption {
            get {
                return ResourceManager.GetString("PreferencesDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při nahrávání projektu nastaly chyby.
        /// </summary>
        internal static string ProjectLoadErrorCaption {
            get {
                return ResourceManager.GetString("ProjectLoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyl nalezen cílový soubor.
        /// </summary>
        internal static string ProjectLoadFileNotFound {
            get {
                return ResourceManager.GetString("ProjectLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný formát XML.
        /// </summary>
        internal static string ProjectLoadInvalidFormat {
            get {
                return ResourceManager.GetString("ProjectLoadInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba záznamu.
        /// </summary>
        internal static string PropertiesCannotWriteCaption {
            get {
                return ResourceManager.GetString("PropertiesCannotWriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze nastavit vlastnost krabičky, protože ji uzamkla jiná krabička.
        /// </summary>
        internal static string PropertiesCannotWriteText {
            get {
                return ResourceManager.GetString("PropertiesCannotWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnosti.
        /// </summary>
        internal static string PropertiesContentText {
            get {
                return ResourceManager.GetString("PropertiesContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstupní.
        /// </summary>
        internal static string PropertiesOutputConnector {
            get {
                return ResourceManager.GetString("PropertiesOutputConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavte propojení pro tuto zásuvku.
        /// </summary>
        internal static string PropertyConnectorDescription {
            get {
                return ResourceManager.GetString("PropertyConnectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba nastavení vlastnosti:.
        /// </summary>
        internal static string PropertyMoreBoxesErrorCaption {
            get {
                return ResourceManager.GetString("PropertyMoreBoxesErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadováné nastavení vlastnosti u více krabiček se nezdařilo - jedna nebo více krabiček je zamčená.
        /// </summary>
        internal static string PropertyMoreBoxesErrorText {
            get {
                return ResourceManager.GetString("PropertyMoreBoxesErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Určuje, jestli je daná vlastnost vidět jako zásuvka.
        /// </summary>
        internal static string PropertySocketHint {
            get {
                return ResourceManager.GetString("PropertySocketHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viditelné zásuvky.
        /// </summary>
        internal static string PropertySocketName {
            get {
                return ResourceManager.GetString("PropertySocketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit pracovní plochu.
        /// </summary>
        internal static string RemoveDesktopDialogCaption {
            get {
                return ResourceManager.GetString("RemoveDesktopDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        internal static string RemoveDesktopDialogOK {
            get {
                return ResourceManager.GetString("RemoveDesktopDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte nové jméno krabičky.
        /// </summary>
        internal static string RenameDialogCaption {
            get {
                return ResourceManager.GetString("RenameDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavit do vlastnosti jinou hodnotu.
        /// </summary>
        internal static string StringComboAddingControlButtonText {
            get {
                return ResourceManager.GetString("StringComboAddingControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte jinou hodnotu:.
        /// </summary>
        internal static string StringComboAddingControlText {
            get {
                return ResourceManager.GetString("StringComboAddingControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelská poznámka.
        /// </summary>
        internal static string UserNote {
            get {
                return ResourceManager.GetString("UserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelská poznámka: .
        /// </summary>
        internal static string UserNoteCaption {
            get {
                return ResourceManager.GetString("UserNoteCaption", resourceCulture);
            }
        }
    }
}
