//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditFuzzyCategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditFuzzyCategories.Localization_en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The A value of the trapezoid should be less than maximal value of the attribute.
        /// </summary>
        internal static string ABiggerThanMax {
            get {
                return ResourceManager.GetString("ABiggerThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fuzzy set must be of trapeziodal shape, that is A &lt; D &lt; C &lt; B..
        /// </summary>
        internal static string ADCB {
            get {
                return ResourceManager.GetString("ADCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fuzzy category.
        /// </summary>
        internal static string AddFC {
            get {
                return ResourceManager.GetString("AddFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fuzzy category having the same name is already defined. Names of fuzzy categories have to be unique..
        /// </summary>
        internal static string AlreadyContainsName {
            get {
                return ResourceManager.GetString("AlreadyContainsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trapezoidal fuzzy category having the same values is already defined. Please change the values of the trapezoid..
        /// </summary>
        internal static string AlreadyContainsValues {
            get {
                return ResourceManager.GetString("AlreadyContainsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (start of the trapeziod):.
        /// </summary>
        internal static string ATB {
            get {
                return ResourceManager.GetString("ATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The B value of the trapezoid should be bigger than minimal value of the attribute.
        /// </summary>
        internal static string BLowerThanMin {
            get {
                return ResourceManager.GetString("BLowerThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B (end of the trapezoid):.
        /// </summary>
        internal static string BTB {
            get {
                return ResourceManager.GetString("BTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C (descending peak):.
        /// </summary>
        internal static string CTB {
            get {
                return ResourceManager.GetString("CTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D (ascending peak):.
        /// </summary>
        internal static string DTB {
            get {
                return ResourceManager.GetString("DTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit fuzzy category.
        /// </summary>
        internal static string EditFC {
            get {
                return ResourceManager.GetString("EditFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit fuzzy categories.
        /// </summary>
        internal static string EditFuzzyCategories {
            get {
                return ResourceManager.GetString("EditFuzzyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul for editing fuzzy categories.
        /// </summary>
        internal static string EditFuzzyCategoriesAbout {
            get {
                return ResourceManager.GetString("EditFuzzyCategoriesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing fuzzy categories.
        /// </summary>
        internal static string ExistingFuzzyCategories {
            get {
                return ResourceManager.GetString("ExistingFuzzyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fuzzy category is selected.
        /// </summary>
        internal static string ItemNotSelected {
            get {
                return ResourceManager.GetString("ItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCFAR compatibility.
        /// </summary>
        internal static string LCFAR {
            get {
                return ResourceManager.GetString("LCFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the distinct values of the column is not covered by any fuzzy category. This is not compatible with LCFAR..
        /// </summary>
        internal static string LCFARIncompatible {
            get {
                return ResourceManager.GetString("LCFARIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NewFCName {
            get {
                return ResourceManager.GetString("NewFCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New fuzzy category.
        /// </summary>
        internal static string NewFuzzyCategory {
            get {
                return ResourceManager.GetString("NewFuzzyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the new fuzzy category is not set.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The peak value of the new trapezoid is overlapping with peak value of other already defined trapeziod. This is not allowed in LFCAR..
        /// </summary>
        internal static string Overlapping {
            get {
                return ResourceManager.GetString("Overlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove fuzzy category.
        /// </summary>
        internal static string RemoveFC {
            get {
                return ResourceManager.GetString("RemoveFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save fuzzy category.
        /// </summary>
        internal static string SaveFC {
            get {
                return ResourceManager.GetString("SaveFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values A, B, C, D are either not filled, or in invalid non-numerical format.
        /// </summary>
        internal static string TrapezoidInvalidFormat {
            get {
                return ResourceManager.GetString("TrapezoidInvalidFormat", resourceCulture);
            }
        }
    }
}
