//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditFuzzyCategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditFuzzyCategories.Localization_cs-CZ", typeof(Localization_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat fuzzy kategorii.
        /// </summary>
        internal static string AddFC {
            get {
                return ResourceManager.GetString("AddFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (začátek lichobězníku):.
        /// </summary>
        internal static string ATB {
            get {
                return ResourceManager.GetString("ATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B (konec lichoběžníku):.
        /// </summary>
        internal static string BTB {
            get {
                return ResourceManager.GetString("BTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C (koncový vrchol):.
        /// </summary>
        internal static string CTB {
            get {
                return ResourceManager.GetString("CTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D (počáteční vrchol):.
        /// </summary>
        internal static string DTB {
            get {
                return ResourceManager.GetString("DTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editovat fuzzy kategorii.
        /// </summary>
        internal static string EditFC {
            get {
                return ResourceManager.GetString("EditFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editace fuzzy kategorií.
        /// </summary>
        internal static string EditFuzzyCategories {
            get {
                return ResourceManager.GetString("EditFuzzyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul pro úpravu fuzzy kategorií.
        /// </summary>
        internal static string EditFuzzyCategoriesAbout {
            get {
                return ResourceManager.GetString("EditFuzzyCategoriesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existující fuzzy kategorie.
        /// </summary>
        internal static string ExistingFuzzyCategories {
            get {
                return ResourceManager.GetString("ExistingFuzzyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno:.
        /// </summary>
        internal static string NewFCName {
            get {
                return ResourceManager.GetString("NewFCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová fuzzy kategorie.
        /// </summary>
        internal static string NewFuzzyCategory {
            get {
                return ResourceManager.GetString("NewFuzzyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit fuzzy kategorii.
        /// </summary>
        internal static string RemoveFC {
            get {
                return ResourceManager.GetString("RemoveFC", resourceCulture);
            }
        }
    }
}
