//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferda.FrontEnd.AddIns.EditCategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferda.FrontEnd.AddIns.EditCategories.Localization_cs-CZ", typeof(Localization_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný výraz pro výběr sloupce.
        /// </summary>
        internal static string BadColumnSelectExpression {
            get {
                return ResourceManager.GetString("BadColumnSelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný řetězec pro připojení.
        /// </summary>
        internal static string BadConnectionString {
            get {
                return ResourceManager.GetString("BadConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervaly v jedné kategorii musejí být stejného druhu.
        /// </summary>
        internal static string BadIntervalType {
            get {
                return ResourceManager.GetString("BadIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krabička není zapojena.
        /// </summary>
        internal static string BoxNotConnected {
            get {
                return ResourceManager.GetString("BoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string ButtonAddText {
            get {
                return ResourceManager.GetString("ButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat do kategorie.
        /// </summary>
        internal static string ButtonCheck {
            get {
                return ResourceManager.GetString("ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdělit vše rekurzivně.
        /// </summary>
        internal static string ButtonFlatten {
            get {
                return ResourceManager.GetString("ButtonFlatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spojit.
        /// </summary>
        internal static string ButtonJoin {
            get {
                return ResourceManager.GetString("ButtonJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit bez uložení.
        /// </summary>
        internal static string ButtonQuitWithoutSave {
            get {
                return ResourceManager.GetString("ButtonQuitWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string ButtonRemoveText {
            get {
                return ResourceManager.GetString("ButtonRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejmenovat.
        /// </summary>
        internal static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit a ukončit.
        /// </summary>
        internal static string ButtonSaveAndQuit {
            get {
                return ResourceManager.GetString("ButtonSaveAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdělit.
        /// </summary>
        internal static string ButtonSplit {
            get {
                return ResourceManager.GetString("ButtonSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdělit rekurzivně.
        /// </summary>
        internal static string ButtonSplitRecursive {
            get {
                return ResourceManager.GetString("ButtonSplitRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název kategorie.
        /// </summary>
        internal static string ColumnCategoryName {
            get {
                return ResourceManager.GetString("ColumnCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh kategorie.
        /// </summary>
        internal static string ColumnCategoryType {
            get {
                return ResourceManager.GetString("ColumnCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota kategorie.
        /// </summary>
        internal static string ColumnCategoryValue {
            get {
                return ResourceManager.GetString("ColumnCategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frekvence.
        /// </summary>
        internal static string ColumnFrequency {
            get {
                return ResourceManager.GetString("ColumnFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit kategorie.
        /// </summary>
        internal static string EditCategories {
            get {
                return ResourceManager.GetString("EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul pro úpravu kategorii.
        /// </summary>
        internal static string EditCategoriesAbout {
            get {
                return ResourceManager.GetString("EditCategoriesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte správně všechny parametry.
        /// </summary>
        internal static string InsufficientIntervalParameters {
            get {
                return ResourceManager.GetString("InsufficientIntervalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval může být přidán.
        /// </summary>
        internal static string IntervalCanBeAdded {
            get {
                return ResourceManager.GetString("IntervalCanBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval je disjunktní.
        /// </summary>
        internal static string IntervalIsDisjunct {
            get {
                return ResourceManager.GetString("IntervalIsDisjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval není disjunktní.
        /// </summary>
        internal static string IntervalIsNotDisjunct {
            get {
                return ResourceManager.GetString("IntervalIsNotDisjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný interval.
        /// </summary>
        internal static string InvalidIntervalError {
            get {
                return ResourceManager.GetString("InvalidIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přípustné hodnoty.
        /// </summary>
        internal static string LabelAvailableValues {
            get {
                return ResourceManager.GetString("LabelAvailableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsažené hodnoty.
        /// </summary>
        internal static string LabelExistingValues {
            get {
                return ResourceManager.GetString("LabelExistingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervaly (dvojklik pro smazání).
        /// </summary>
        internal static string LabelIntervals {
            get {
                return ResourceManager.GetString("LabelIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh intervalu.
        /// </summary>
        internal static string LabelIntervalType {
            get {
                return ResourceManager.GetString("LabelIntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ spodní hranice.
        /// </summary>
        internal static string LabelLeftBoundType {
            get {
                return ResourceManager.GetString("LabelLeftBoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota spodní hranice.
        /// </summary>
        internal static string LabelLeftBoundValue {
            get {
                return ResourceManager.GetString("LabelLeftBoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový název.
        /// </summary>
        internal static string LabelNewName {
            get {
                return ResourceManager.GetString("LabelNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ horní hranice.
        /// </summary>
        internal static string LabelRightBoundType {
            get {
                return ResourceManager.GetString("LabelRightBoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota horní hranice.
        /// </summary>
        internal static string LabeRightBoundValue {
            get {
                return ResourceManager.GetString("LabeRightBoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový výčet.
        /// </summary>
        internal static string NewEnumeration {
            get {
                return ResourceManager.GetString("NewEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový interval.
        /// </summary>
        internal static string NewInterval {
            get {
                return ResourceManager.GetString("NewInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová kategorie.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie nemůže být prázdná.
        /// </summary>
        internal static string NoEmptyCategoryAllowed {
            get {
                return ResourceManager.GetString("NoEmptyCategoryAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - inf.
        /// </summary>
        internal static string RadioMinusInfinity {
            get {
                return ResourceManager.GetString("RadioMinusInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + inf.
        /// </summary>
        internal static string RadioPlusInfinity {
            get {
                return ResourceManager.GetString("RadioPlusInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie se stejným názvem nejsou povoleny.
        /// </summary>
        internal static string SameCategoryNames {
            get {
                return ResourceManager.GetString("SameCategoryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string TypeInterval {
            get {
                return ResourceManager.GetString("TypeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výčet.
        /// </summary>
        internal static string TypeSet {
            get {
                return ResourceManager.GetString("TypeSet", resourceCulture);
            }
        }
    }
}
