//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferda.FrontEnd.AddIns.EditCategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferda.FrontEnd.AddIns.EditCategories.Localization_en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad column select expression.
        /// </summary>
        internal static string BadColumnSelectExpression {
            get {
                return ResourceManager.GetString("BadColumnSelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad connection string.
        /// </summary>
        internal static string BadConnectionString {
            get {
                return ResourceManager.GetString("BadConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box not connected.
        /// </summary>
        internal static string BoxNotConnected {
            get {
                return ResourceManager.GetString("BoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string ButtonAddText {
            get {
                return ResourceManager.GetString("ButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string ButtonCheck {
            get {
                return ResourceManager.GetString("ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split recursive all.
        /// </summary>
        internal static string ButtonFlatten {
            get {
                return ResourceManager.GetString("ButtonFlatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string ButtonJoin {
            get {
                return ResourceManager.GetString("ButtonJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit without save.
        /// </summary>
        internal static string ButtonQuitWithoutSave {
            get {
                return ResourceManager.GetString("ButtonQuitWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string ButtonRemoveText {
            get {
                return ResourceManager.GetString("ButtonRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and quit.
        /// </summary>
        internal static string ButtonSaveAndQuit {
            get {
                return ResourceManager.GetString("ButtonSaveAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string ButtonSplit {
            get {
                return ResourceManager.GetString("ButtonSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split recursive.
        /// </summary>
        internal static string ButtonSplitRecursive {
            get {
                return ResourceManager.GetString("ButtonSplitRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string ColumnCategoryName {
            get {
                return ResourceManager.GetString("ColumnCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type.
        /// </summary>
        internal static string ColumnCategoryType {
            get {
                return ResourceManager.GetString("ColumnCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category value.
        /// </summary>
        internal static string ColumnCategoryValue {
            get {
                return ResourceManager.GetString("ColumnCategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string ColumnFrequency {
            get {
                return ResourceManager.GetString("ColumnFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit categories.
        /// </summary>
        internal static string EditCategories {
            get {
                return ResourceManager.GetString("EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit categories module.
        /// </summary>
        internal static string EditCategoriesAbout {
            get {
                return ResourceManager.GetString("EditCategoriesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input correct interval parameters.
        /// </summary>
        internal static string InsufficientIntervalParameters {
            get {
                return ResourceManager.GetString("InsufficientIntervalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval can be added.
        /// </summary>
        internal static string IntervalCanBeAdded {
            get {
                return ResourceManager.GetString("IntervalCanBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval is disjunct.
        /// </summary>
        internal static string IntervalIsDisjunct {
            get {
                return ResourceManager.GetString("IntervalIsDisjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval is not disjunct.
        /// </summary>
        internal static string IntervalIsNotDisjunct {
            get {
                return ResourceManager.GetString("IntervalIsNotDisjunct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval.
        /// </summary>
        internal static string InvalidIntervalError {
            get {
                return ResourceManager.GetString("InvalidIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available values.
        /// </summary>
        internal static string LabelAvailableValues {
            get {
                return ResourceManager.GetString("LabelAvailableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing values.
        /// </summary>
        internal static string LabelExistingValues {
            get {
                return ResourceManager.GetString("LabelExistingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left bound type.
        /// </summary>
        internal static string LabelLeftBoundType {
            get {
                return ResourceManager.GetString("LabelLeftBoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left bound value.
        /// </summary>
        internal static string LabelLeftBoundValue {
            get {
                return ResourceManager.GetString("LabelLeftBoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string LabelNewName {
            get {
                return ResourceManager.GetString("LabelNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right bound type.
        /// </summary>
        internal static string LabelRightBoundType {
            get {
                return ResourceManager.GetString("LabelRightBoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right bound value.
        /// </summary>
        internal static string LabelRightBoundValue {
            get {
                return ResourceManager.GetString("LabelRightBoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New enumeration.
        /// </summary>
        internal static string NewEnumeration {
            get {
                return ResourceManager.GetString("NewEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New interval.
        /// </summary>
        internal static string NewInterval {
            get {
                return ResourceManager.GetString("NewInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - inf.
        /// </summary>
        internal static string RadioMinusInfinity {
            get {
                return ResourceManager.GetString("RadioMinusInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + inf.
        /// </summary>
        internal static string RadioPlusInfinity {
            get {
                return ResourceManager.GetString("RadioPlusInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories of the same name are not allowed.
        /// </summary>
        internal static string SameCategoryNames {
            get {
                return ResourceManager.GetString("SameCategoryNames", resourceCulture);
            }
        }
    }
}
