/* Generated by Together */

using System;
using System.Collections;
using System.Drawing;
using System.Windows.Forms;
using System.IO;

using Ferda.ModulesManager;
using Ferda.Modules;


namespace Ferda.FrontEnd.Desktop 
{
    /// <summary>
	/// Repository of all svg strings for all boxmodules in the system.
    /// Class will provide additional functionality for extracting GDI+
    /// code from svg
	/// </summary>
	///<stereotype>container</stereotype>
    public class SVGManager
	{
        /// <summary>
        /// Default constructor - for now loads the socket and box bitmaps
        /// </summary>
        public SVGManager()
        {
            socket = new Bitmap("socket.bmp");
            box = new Bitmap("box.bmp");
        }

        //Hashtables for storing the bitmaps for sockets and boxes
        //private Dictionary<ISocket,  Bitmap> socketBitmaps;
        //private Dictionary<IBoxModule, Bitmap> boxBitmaps;
        private Bitmap socket;
        private Bitmap box;

        /// <summary>
        /// Function returns the bitmap of the BoxModule. It creates the bitmap
        /// from the SVG if the bitmap is not created
        /// </summary>
        /// <param name="boxModule">Box that wants the bitmap</param>
        /// <returns>Bitmap of the box</returns>
        public Bitmap GetBoxBitmap(ModulesManager.IBoxModule boxModule)
        {
            //planovany postup:
            //1. Zjisti se IFactoryCreator, z neho se vezme Identifier nebo Label
            //2. Podiva se do boxBitmaps jestli uz tam takova bitmapa je
            //3. Vrati bitmapu, jestli ne tak ji pomoci SVG vytvori a potom ji vrati

            if (boxModule.MadeInCreator.Icon.Length != 0)
            {
                MemoryStream stream = new MemoryStream(boxModule.MadeInCreator.Icon);
                Icon icon = new Icon(stream);
                return icon.ToBitmap();
            }
            else
            {
                return box;
            }
        }

        /// <summary>
        /// Function returns the bitmap of the associated Socket. It creates the bitmap
        /// from the SVG if the bitmap is not created
        /// </summary>
        /// <param name="socket">Socket that wants the bitmap</param>
        /// <returns>bitmap of the socket</returns>
        public Bitmap GetSocketBitmap(SocketInfo socket)
        {
            //Postup obdobny jako u GetBox Bitmap

            return this.socket;
        }
	}
}
