/* Generated by Together */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using System.IO;

using Ferda.ModulesManager;
using Ferda.Modules;
using SharpVectors.Dom.Svg;
using SharpVectors.Renderer.Gdi;


namespace Ferda.FrontEnd.Desktop 
{
    /// <summary>
	/// Repository of all svg strings for all boxmodules in the system.
    /// Class will provide additional functionality for extracting GDI+
    /// code from svg
	/// </summary>
	///<stereotype>container</stereotype>
    public class SVGManager
	{
        /// <summary>
        /// Default constructor - for now loads the socket and box bitmaps
        /// </summary>
        public SVGManager(Control control)
        {
            socket = new Bitmap("socket.bmp");
            box = new Bitmap("box.bmp");

            boxBitmaps = new Dictionary<string, Bitmap>();
            myControl = control;
        }

        //HashTable for storing the bitmaps of svgs of boxes
        private Dictionary<string, Bitmap> boxBitmaps;
        
        /// <summary>
        /// The socket image when there is no socket svg (there can be one)
        /// </summary>
        private Bitmap socket;
        /// <summary>
        /// The box image when there is no boxDesign.svg file of the box
        /// </summary>
        private Bitmap box;

        /// <summary>
        /// Required by SharpVectorLibrary to paint on some control
        /// </summary>
        private Control myControl;

        /// <summary>
        /// Function returns the bitmap of the BoxModule. It creates the bitmap
        /// from the SVG if the bitmap is not created
        /// </summary>
        /// <param name="boxModule">Box that wants the bitmap</param>
        /// <returns>Bitmap of the box</returns>
        public Bitmap GetBoxBitmap(ModulesManager.IBoxModule boxModule)
        {
            IBoxModuleFactoryCreator creator = boxModule.MadeInCreator;

            //prozatim je to takhle
            if (creator.Icon.Length != 0)
            {
                MemoryStream stream = new MemoryStream(boxModule.MadeInCreator.Icon);
                Icon icon = new Icon(stream);
                return icon.ToBitmap();
            }
            else
            {
                return box;
            }

            //bude to ale takhle
            //if (boxBitmaps.ContainsKey(creator.Identifier))
            //{
            //    return boxBitmaps[creator.Identifier];
            //}
            //else
            //{
            //    there is a svg design file
            //    if (creator.Design != string.Empty)
            //    {
            //        SvgWindow window;
            //        GdiRenderer renderer;

            //        setting up the renderer and the svgWindow
            //        renderer = new GdiRenderer();
            //        window = new SvgWindow(myControl, renderer);
            //        SvgDocument document = new SvgDocument(window);
            //        document.LoadXml(creator.Design);

            //        renderer.Render(window.Document as SvgDocument);
            //        Bitmap image = renderer.RasterImage;

            //        boxBitmaps.Add(creator.Identifier, image);
            //        return image;
            //    }
            //    there is no svg design file
            //    else
            //    {
            //        return box;
            //    }
            //}
        }

        /// <summary>
        /// Function returns the bitmap of the associated Socket. It creates the bitmap
        /// from the SVG if the bitmap is not created
        /// </summary>
        /// <param name="socket">Socket that wants the bitmap</param>
        /// <returns>bitmap of the socket</returns>
        public Bitmap GetSocketBitmap(SocketInfo socket)
        {
            //Postup obdobny jako u GetBox Bitmap

            return this.socket;
        }
	}
}
