//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.AddIns.ColumnFrequency {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontEnd.AddIns.ColumnFrequency.Localization_cs-CZ", typeof(Localization_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný výraz pro výběr sloupce.
        /// </summary>
        internal static string BadColumnSelectExpression {
            get {
                return ResourceManager.GetString("BadColumnSelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný řetězec pro připojení.
        /// </summary>
        internal static string BadConnectionString {
            get {
                return ResourceManager.GetString("BadConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krabička není zapojena.
        /// </summary>
        internal static string BoxNotConnected {
            get {
                return ResourceManager.GetString("BoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frekvence.
        /// </summary>
        internal static string ColumnFrequency {
            get {
                return ResourceManager.GetString("ColumnFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plošný graf frekvencí.
        /// </summary>
        internal static string ColumnFrequencyAreaChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloupcový graf frekvencí.
        /// </summary>
        internal static string ColumnFrequencyBarChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul pro zobrazování frekvencí.
        /// </summary>
        internal static string ColumnFrequencyModule {
            get {
                return ResourceManager.GetString("ColumnFrequencyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsečový graf frekvencí.
        /// </summary>
        internal static string ColumnFrequencyPieChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkopírovat všechny položky do schránky.
        /// </summary>
        internal static string CopyAllToClipboard {
            get {
                return ResourceManager.GetString("CopyAllToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkopírovat graf do schránky.
        /// </summary>
        internal static string CopyChart {
            get {
                return ResourceManager.GetString("CopyChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkopírovat vybrané položky do schránky.
        /// </summary>
        internal static string CopySelectedToClipboard {
            get {
                return ResourceManager.GetString("CopySelectedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frekvence.
        /// </summary>
        internal static string FrequencyColumn {
            get {
                return ResourceManager.GetString("FrequencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápověda.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné parametry.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent.
        /// </summary>
        internal static string PercentageColumn {
            get {
                return ResourceManager.GetString("PercentageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klikněte pravým tlačítkem pro volby kopírování.
        /// </summary>
        internal static string RightClickToCopySelected {
            get {
                return ResourceManager.GetString("RightClickToCopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit legendu.
        /// </summary>
        internal static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plošný graf.
        /// </summary>
        internal static string TabPageAreaChart {
            get {
                return ResourceManager.GetString("TabPageAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloupcový graf.
        /// </summary>
        internal static string TabPageBarChart {
            get {
                return ResourceManager.GetString("TabPageBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsečový graf.
        /// </summary>
        internal static string TabPagePieChart {
            get {
                return ResourceManager.GetString("TabPagePieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string TabPageText {
            get {
                return ResourceManager.GetString("TabPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit popisky.
        /// </summary>
        internal static string ToggleMarks {
            get {
                return ResourceManager.GetString("ToggleMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolutní.
        /// </summary>
        internal static string ToolStripMenuItemAbsolute {
            get {
                return ResourceManager.GetString("ToolStripMenuItemAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        internal static string ValueColumn {
            get {
                return ResourceManager.GetString("ValueColumn", resourceCulture);
            }
        }
    }
}
