//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.AddIns.ColumnFrequency {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontEnd.AddIns.ColumnFrequency.Localization_en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad column select expression.
        /// </summary>
        internal static string BadColumnSelectExpression {
            get {
                return ResourceManager.GetString("BadColumnSelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad connection string.
        /// </summary>
        internal static string BadConnectionString {
            get {
                return ResourceManager.GetString("BadConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box not connected.
        /// </summary>
        internal static string BoxNotConnected {
            get {
                return ResourceManager.GetString("BoxNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frequency.
        /// </summary>
        internal static string ColumnFrequency {
            get {
                return ResourceManager.GetString("ColumnFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies area chart.
        /// </summary>
        internal static string ColumnFrequencyAreaChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies bar chart.
        /// </summary>
        internal static string ColumnFrequencyBarChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency displayer module.
        /// </summary>
        internal static string ColumnFrequencyModule {
            get {
                return ResourceManager.GetString("ColumnFrequencyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies pie chart.
        /// </summary>
        internal static string ColumnFrequencyPieChart {
            get {
                return ResourceManager.GetString("ColumnFrequencyPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all items to clipboard.
        /// </summary>
        internal static string CopyAllToClipboard {
            get {
                return ResourceManager.GetString("CopyAllToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy chart to clipboard.
        /// </summary>
        internal static string CopyChart {
            get {
                return ResourceManager.GetString("CopyChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items to clipboard.
        /// </summary>
        internal static string CopySelectedToClipboard {
            get {
                return ResourceManager.GetString("CopySelectedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string FrequencyColumn {
            get {
                return ResourceManager.GetString("FrequencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters input.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string PercentageColumn {
            get {
                return ResourceManager.GetString("PercentageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right-click for copy options.
        /// </summary>
        internal static string RightClickToCopySelected {
            get {
                return ResourceManager.GetString("RightClickToCopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend.
        /// </summary>
        internal static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area chart.
        /// </summary>
        internal static string TabPageAreaChart {
            get {
                return ResourceManager.GetString("TabPageAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar chart.
        /// </summary>
        internal static string TabPageBarChart {
            get {
                return ResourceManager.GetString("TabPageBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie chart.
        /// </summary>
        internal static string TabPagePieChart {
            get {
                return ResourceManager.GetString("TabPagePieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string TabPageText {
            get {
                return ResourceManager.GetString("TabPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show labels.
        /// </summary>
        internal static string ToggleMarks {
            get {
                return ResourceManager.GetString("ToggleMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        internal static string ToolStripMenuItemAbsolute {
            get {
                return ResourceManager.GetString("ToolStripMenuItemAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueColumn {
            get {
                return ResourceManager.GetString("ValueColumn", resourceCulture);
            }
        }
    }
}
