/* Generated by Together */

using System;
using Ice;

namespace Ferda {
    namespace ModulesManager {

        /// <summary>
        /// Summary description for the class.
        /// </summary>

        public class BoxModuleProjectInformationI : BoxModuleProjectInformationDisp_
		{
			
			///<summary>
			/// Constructor
			/// </summary>
			/// <param name="modulesManager">A  ModulesManager</param>
			public BoxModuleProjectInformationI(ModulesManager modulesManager)
			{
				this.modulesManager = modulesManager;
			}

            /// <summary>
            /// Method getUserLabel
            /// </summary>
            /// <returns>A string</returns>
            /// <param name="boxModuleIceIdentity">A  string</param>
            /// <param name="__current">An Ice.Current</param>
            public override string getUserLabel(string boxModuleIceIdentity, Current __current) {
                BoxModule box = modulesManager.getBoxModuleByIdentity(boxModuleIceIdentity);
				if(box!=null)
				{
					return box.UserName;
				}
				throw new BoxModuleNotExistError();
            }

            /// <summary>
            /// Method getUserHint
            /// </summary>
            /// <returns>A string</returns>
            /// <param name="boxModuleIceIdentity">A  string</param>
            /// <param name="__current">An Ice.Current</param>
            public override string getUserHint(string boxModuleIceIdentity, Current __current) {
                BoxModule box = modulesManager.getBoxModuleByIdentity(boxModuleIceIdentity);
				if(box!=null)
				{
					return box.UserHint;
				}
				throw new BoxModuleNotExistError();
            }

            /// <summary>
            /// Method getProjectIdentifier
            /// </summary>
            /// <returns>A string</returns>
            /// <param name="boxModuleIceIdentity">A  string</param>
            /// <param name="__current">An Ice.Current</param>
            public override int getProjectIdentifier(string boxModuleIceIdentity, Current __current) {
                BoxModule box = modulesManager.getBoxModuleByIdentity(boxModuleIceIdentity);
				if(box!=null)
				{
					return box.ProjectIdentifier;
				}
				throw new BoxModuleNotExistError();
            }
			
			private ModulesManager modulesManager;
        }

    }
}
