/* Generated by Together */

using System;
using Ice;

namespace Ferda {
    namespace ModulesManager {

        /// <summary>
        /// Summary description for the class.
        /// </summary>
        public class BoxModuleLockerI : BoxModuleLockerDisp_
		{
			
			///<summary>
			/// Constructor
			/// </summary>
			/// <param name="modulesManager">A  ModulesManager</param>
			public BoxModuleLockerI(ModulesManager modulesManager)
			{
				this.modulesManager = modulesManager;
			}

            /// <summary>
            /// Method lockBoxModule
            /// </summary>
            /// <param name="boxModuleIceIdentity">A string</param>
            /// <param name="__current">An Ice.Current</param>
            public override void lockBoxModule(String boxModuleIceIdentity, Current __current) {
                BoxModule box = modulesManager.getBoxModuleByIdentity(boxModuleIceIdentity);
				if(box!=null)
				{
					box.Lock();
				}
				else throw new BoxModuleNotExistError();
            }

            /// <summary>
            /// Method unlockBoxModule
            /// </summary>
            /// <param name="boxModuleIceIdentity">A string</param>
            /// <param name="__current">An Ice.Current</param>
            public override void unlockBoxModule(String boxModuleIceIdentity, Current __current) {
                BoxModule box = modulesManager.getBoxModuleByIdentity(boxModuleIceIdentity);
				if(box!=null)
				{
					box.Unlock();
				}
				else throw new BoxModuleNotExistError();
            }
			
			private ModulesManager modulesManager;
        }
    }
}
