/* Generated by Together */

using System;
using Ice;
using System.Diagnostics;

namespace Ferda {
	namespace ModulesManager {

		/// <summary>
		/// Summary description for the class.
		/// </summary>
		public class Helper : IAppPrefs, IIceHelper, IIcePrefs
		{
			public Helper(Ice.ObjectAdapter adapter, string[] localePrefs, ModulesManager manager)
			{
				this.adapter = adapter;
				this.localePrefs = localePrefs;
				Debug.WriteLine("Creating BoxModuleIceFactories...");
				this.boxModuleIceFactories = new BoxModuleIceFactories( this );
				Debug.WriteLine("Creating ManagersEngine...");
				this.managersEngineI = new ManagersEngineI(adapter,this, manager);
				this.managersEnginePrx = ManagersEnginePrxHelper.uncheckedCast(
					adapter.addWithUUID(managersEngineI));
			}
			
			public ObjectAdapter ObjectAdapter
			{
				get {
					return adapter;
				}
			}
			
			public BoxModuleIceFactories BoxModuleIceFactories
			{
				get {
					return this.boxModuleIceFactories;
				}
			}
			
			public ManagersEngineI ManagersEngineI
			{
				get {
					return this.managersEngineI;
				}
			}
			
			public ManagersEnginePrx ManagersEnginePrx
			{
				get {
					return this.managersEnginePrx;
				}
			}
			
			public String[] LocalePrefs
			{
				get {
					return this.localePrefs;
				}
			}
			
			private String[] localePrefs;
			private Ice.ObjectAdapter adapter;
			private BoxModuleIceFactories boxModuleIceFactories;
			private ManagersEngineI managersEngineI;
			private ManagersEnginePrx managersEnginePrx;
		}
	}
}
