/* Generated by Together */

using System;

namespace Ferda {
	namespace ModulesManager {

public interface IAppPrefs {
            String[] LocalePrefs {
                get;
            }
}
	}
}
