/* Generated by Together */

using System;

namespace Ferda {
	namespace ModulesManager {

public interface IIcePrefs {
            Ice.ObjectAdapter ObjectAdapter {
				get;
            }
}
	}
}
