/* Generated by Together */

using System;
using Ferda.Modules;


namespace Ferda {
    namespace ModulesManager {
		public class ModuleForInteractionInfo {

			public ModuleForInteractionInfo(ModuleForInteractionPrx prx, Helper helper)
			{
				this.neededConectedSockets = prx.getNeededConnectedSockets();
				this.acceptedBoxTypes = prx.getAcceptedBoxTypes();
				this.label = prx.getLabel(helper.LocalePrefs);
				this.hint = prx.getHint(helper.LocalePrefs);
				this.helpInfo = prx.getHelpFileInfoSeq(helper.LocalePrefs);
				this.dynamicHelp = prx.getDynamicHelpItems(helper.LocalePrefs);
				this.icon = prx.getIcon();
				this.iceIdentity = Ice.Util.identityToString(prx.ice_getIdentity());
			}
			
        	private string[] neededConectedSockets;
			private BoxType[] acceptedBoxTypes;
			private string label;
			private string hint;
			private HelpFileInfo[] helpInfo;
			private DynamicHelpItem[] dynamicHelp;
			private byte[] icon;
            private string iceIdentity;
			
			public string[] NeededConectedSockets
			{
				get {
					return neededConectedSockets;
				}
			}
			
			public BoxType[] AcceptedBoxTypes
			{
				get {
					return acceptedBoxTypes;
				}
			}
			
			public string Label
			{
				get {
					return label;
				}
			}
			
			public string Hint
			{
				get {
					return hint;
				}
			}
			
			public HelpFileInfo[] HelpInfo
			{
				get {
					return helpInfo;
				}
			}
			
			public DynamicHelpItem[] DynamicHelp
			{
				get {
					return dynamicHelp;
				}
			}
			
			public byte[] Icon
			{
				get {
					return icon;
				}
			}
			
			public string IceIdentity
			{
				get {
					return iceIdentity;
				}
			}
		}
    }
}
