/* Generated by Together */

using System;
using Ice;

namespace Ferda {
    namespace ModulesManager {

        /// <summary>
        /// Summary description for the class.
        /// </summary>

        public class OutputI : OutputDisp_ {

            /// <summary>
            /// Method writeMsg
            /// </summary>
            /// <param name="type">A  Ferda.ModulesManager.MsgType</param>
            /// <param name="name">A string</param>
            /// <param name="message">A string</param>
            /// <param name="__current">An Ice.Current</param>
            public override void writeMsg(MsgType type, String name, String message, Current __current) {
                string msg = name + ": " + message;
				switch(type)
				{
					case MsgType.Error:
						Console.Error.WriteLine("Error: "+msg);
						break;
					case MsgType.Warning:
						Console.Error.WriteLine("Warning: "+msg);
						break;
					case MsgType.Debug:
						Console.WriteLine("Debug: "+msg);
						break;
					case MsgType.Info:
						Console.WriteLine("Info: "+msg);
						break;
					default:
						Console.WriteLine(msg);
						break;
				}
            }

        }

    }
}
