/* Generated by Together */

using System;

using Ferda.ModulesManager;

namespace Ferda 
{
    namespace FrontEnd 
    {
        namespace ContextHelp 
        {

            ///<summary>
			///Each control that displays a Ferda context help should implement this
			///interface
			///</summary>
            public interface IContextHelpDisplayer
			{
                ///<summary>
                ///The box currently selected in the archive
                ///</summary>
				IBoxModule SelectedBox
                {
                    set;
                    //get;
                }

                ///<summary>
                ///Forces the control to refresh its state
                ///</summary>
                void Adapt();

				///<summary>
				///This function is called when the localization
				///of the application is changed - the whole menu needs to be redrawn
				///</summary>
				void ChangeLocalization();

                /// <summary>
                /// Resets the context help to be without any information
                /// </summary>
                void Reset();
			}
        }
    }
}
